Platform:
  Darwin:
    amd64: https://github.com/ViRb3/wgcf/releases/download/v2.1.4/wgcf_2.1.4_darwin_amd64
  Linux:
    amd64: https://github.com/ViRb3/wgcf/releases/download/v2.1.4/wgcf_2.1.4_linux_amd64
Version: 2.1.4